language: ruby

rvm:
  - "2.3.3"

env:
  -DB=postgresql

before_script:
  - psql -c ‘create database evoke_on_rails_TEST;’ -U postgres

script:
  - RAILS_ENV=test bundle exec rake –trace db:migrate spec
