# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b3e690ae6712f657febfc33da3ef056186688107c69b0cfd07c313d29b7223bb09f9e1ed9049aee7f412fb586524611161ca26c07a615bc5345d6e430624cf7

test:
  secret_key_base: 5126318bdc498fbb2feda9f1478c290174df3d66d31d5e5d15ef39f42cfd37dac82c925c726405c56fba918c30b6e843009c77106efc0e6eb0897d312dbf5820

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
