require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SpaceMembershipsController, type: :controller do

  Devise::Test::ControllerHelpers

  # This should return the minimal set of attributes required to create a valid
  # SpaceMembership. As you add validations to SpaceMembership, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpaceMembershipsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all space_memberships as @space_memberships" do
      space_membership = SpaceMembership.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:space_memberships)).to eq([space_membership])
    end
  end

  describe "GET #show" do
    it "assigns the requested space_membership as @space_membership" do
      space_membership = SpaceMembership.create! valid_attributes
      get :show, params: {id: space_membership.to_param}, session: valid_session
      expect(assigns(:space_membership)).to eq(space_membership)
    end
  end

  describe "GET #new" do
    it "assigns a new space_membership as @space_membership" do
      space_membership = SpaceMembership.create! valid_attributes
      get :new, params: {}, session: valid_session
      expect(assigns(:space_membership)).to be_a_new(space_membership)
    end
  end

  describe "GET #edit" do
    it "assigns the requested space_membership as @space_membership" do
      space_membership = SpaceMembership.create! valid_attributes
      get :edit, params: {id: space_membership.to_param}, session: valid_session
      expect(assigns(:space_membership)).to eq(space_membership)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SpaceMembership" do
        expect {
          post :create, params: {space_membership: valid_attributes}, session: valid_session
        }.to change(SpaceMembership, :count).by(1)
      end

      it "assigns a newly created space_membership as @space_membership" do
        post :create, params: {space_membership: valid_attributes}, session: valid_session
        expect(assigns(:space_membership)).to be_a(SpaceMembership)
        expect(assigns(:space_membership)).to be_persisted
      end

      it "redirects to the created space_membership" do
        post :create, params: {space_membership: valid_attributes}, session: valid_session
        expect(response).to redirect_to(SpaceMembership.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved space_membership as @space_membership" do
        post :create, params: {space_membership: invalid_attributes}, session: valid_session
        expect(assigns(:space_membership)).to be_a_new(SpaceMembership)
      end

      it "re-renders the 'new' template" do
        post :create, params: {space_membership: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested space_membership" do
        space_membership = SpaceMembership.create! valid_attributes
        put :update, params: {id: space_membership.to_param, space_membership: new_attributes}, session: valid_session
        space_membership.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested space_membership as @space_membership" do
        space_membership = SpaceMembership.create! valid_attributes
        put :update, params: {id: space_membership.to_param, space_membership: valid_attributes}, session: valid_session
        expect(assigns(:space_membership)).to eq(space_membership)
      end

      it "redirects to the space_membership" do
        space_membership = SpaceMembership.create! valid_attributes
        put :update, params: {id: space_membership.to_param, space_membership: valid_attributes}, session: valid_session
        expect(response).to redirect_to(space_membership)
      end
    end

    context "with invalid params" do
      it "assigns the space_membership as @space_membership" do
        space_membership = SpaceMembership.create! valid_attributes
        put :update, params: {id: space_membership.to_param, space_membership: invalid_attributes}, session: valid_session
        expect(assigns(:space_membership)).to eq(space_membership)
      end

      it "re-renders the 'edit' template" do
        space_membership = SpaceMembership.create! valid_attributes
        put :update, params: {id: space_membership.to_param, space_membership: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested space_membership" do
      space_membership = SpaceMembership.create! valid_attributes
      expect {
        delete :destroy, params: {id: space_membership.to_param}, session: valid_session
      }.to change(SpaceMembership, :count).by(-1)
    end

    it "redirects to the space_memberships list" do
      space_membership = SpaceMembership.create! valid_attributes
      delete :destroy, params: {id: space_membership.to_param}, session: valid_session
      expect(response).to redirect_to(space_memberships_url)
    end
  end

  describe "GET #join" do
    context "with valid params" do
      it "joins to a new SpaceMembership" do
        expect {
          get :join_space_membership, params: {space_membership: valid_attributes}, session: valid_session
        }.to change(SpaceMembership, :count).by(1)
      end

      it "assigns a newly created space_membership as @space_membership" do
        get :join_space_membership, params: {space_membership: valid_attributes}, session: valid_session
        expect(assigns(:space_membership)).to be_a(SpaceMembership)
        expect(assigns(:space_membership)).to be_persisted
      end

      it "redirects to the created space_membership" do
        get :join_space_membership, params: {space_membership: valid_attributes}, session: valid_session
        expect(response).to redirect_to(SpaceMembership.last)
      end
    end
  end

end
